#!/usr/bin/env bash

# 最初に設定
set -euo pipefail

readonly LOG_OUT=log/out.log
readonly LOG_ERR=log/err.log

function errlog() {
  now=$(date +%Y%m%d_%H-%M-%S)
  local fname=${BASH_SOURCE[1]##*/}
  readonly PROCNAME=${0##*/}
  while read -r line; do
    echo $line
    cat <<EOS >>${LOG_ERR}
$now $PROCNAME (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $line
EOS
    exit 1
  done
}

function outlog() {
  now=$(date +%Y%m%d_%H-%M-%S)
  local fname=${BASH_SOURCE[1]##*/}
  readonly PROCNAME=${0##*/}
  while read -r line; do
    echo $line
    cat <<EOS >>${LOG_OUT}
$now $PROCNAME (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $line
EOS
    exit 1
  done
}
